### ISSUE TITLE
Unable to Execute langgraph up on Windows WSL2: TypeError: cannot unpack non-iterable NoneType object 

### ISSUE THREAD

**Issue by Maks-Redka** [langchain-ai/langgraph-example#21]
# Issue Summary:
Attempting to run langgraph up on Windows WSL2 results in the following error:

```
Traceback (most recent call last):
  File "/home/mex42/work/langgraph-example/.venv/bin/langgraph", line 8, in <module>
    sys.exit(cli())
  File "/home/mex42/work/langgraph-example/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mex42/work/langgraph-example/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mex42/work/langgraph-example/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mex42/work/langgraph-example/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mex42/work/langgraph-example/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mex42/work/langgraph-example/.venv/lib/python3.10/site-packages/langgraph_cli/cli.py", line 183, in up
    capabilities = langgraph_cli.docker.check_capabilities(runner)
  File "/home/mex42/work/langgraph-example/.venv/lib/python3.10/site-packages/langgraph_cli/docker.py", line 83, in check_capabilities
    stdout, _ = runner.run(subp_exec("docker", "info", "-f", "json", collect=True))
TypeError: cannot unpack non-iterable NoneType object
```

Reproduce and issue similar to [Issue #20](https://github.com/langchain-ai/langgraph-example/issues/20)

**Comment by zhao-cs-debug** [comment]
pip install langgraph-cli==0.1.35

**Comment by shanumas** [comment]
@zhao-cs-debug   thanks.  Why doesn't it work with latest version (0.1.41).  But works with 0.1.35.  Why ?
